### ISSUE TITLE
AppStore?

### ISSUE THREAD

**Issue by dr-dimitru** [sdegutis/Vimac#2]
Hey there,

Great idea for the native app.
Any plans to release it in AppStore?

**Comment by dr-dimitru** [comment]
Not all the commands are supported right? Or am I doing something wrong?

**Comment by sdegutis** [comment]
The App Store does not allow apps with features like this (using Accessibility) so no. Also there are very few commands right now.

**Comment by dr-dimitru** [comment]
@sdegutis got it, thank you.
